### ISSUE TITLE
error in the code ?

### ISSUE THREAD

**Issue by ncou** [mykehowells/dotenv#1]
Hi,

I think after looking at your code that there is a mistake with the name of one function line 63.

There is :
if ( strlen( $value ) > 1 && str_starts_with( $value, '"' ) && str_starts_with( $value, '"' ) ) {

and it should be :
if ( strlen( $value ) > 1 && str_starts_with( $value, '"' ) && **str_end_with**( $value, '"' ) ) {

https://github.com/mykemeynell/dotenv/blob/master/env.php#L63

Am i right ? or am i missing something ?

**Comment by mykemeynell** [comment]
That's correct! Nice catch.
